/*
 * AccessPoints.tsx — the Access Points page.
 *
 * Lists the Cisco 9120/9130 access-point inventory and their derived Online/Offline
 * status (inferred every ~2h from switch CDP/LLDP neighbor tables, with the connected
 * switch/interface and last-seen time). Administrators can add, import (CSV/Excel),
 * and remove APs here. Status is inferred evidence, never a fabricated up/down flag.
 */
import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,FileSpreadsheet,Radio,RefreshCw,Upload,Wifi,WifiOff}from'lucide-react';
import'./access-points.css';

type Props={token:string;administrator:boolean};
export default function AccessPoints({token,administrator}:Props){
 const[data,setData]=useState<any>({items:[],summary:{},page:1,pages:1,total:0});const[q,setQ]=useState('');const[site,setSite]=useState('');const[status,setStatus]=useState('');const[model,setModel]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[job,setJob]=useState<any>(null);const[mode,setMode]=useState('replace');const[history,setHistory]=useState<any[]>([]);
 const request=async(path:string,options:RequestInit={})=>{const r=await fetch('/api/v1'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error((await r.json()).detail||'Request failed');return r.json()};
 const[pageSize,setPageSize]=useState(10);
 const load=async(page=1,size=pageSize)=>{setLoading(true);setError('');try{const p=new URLSearchParams({page:String(page),page_size:String(size)});if(q)p.set('q',q);if(site)p.set('site',site);if(status)p.set('status',status);if(model)p.set('model',model);setData(await request('/access-points?'+p));if(administrator)setHistory(await request('/access-points/imports'))}catch(x:any){setError(x.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const models=useMemo(()=>Array.from(new Set(data.items.map((x:any)=>x.ap_model).filter(Boolean))).sort() as string[],[data.items]);
 const validate=async(file?:File)=>{if(!file)return;const fd=new FormData();fd.append('file',file);setError('');try{setJob(await request('/access-points/import/validate',{method:'POST',body:fd}))}catch(x:any){setError(x.message)}};
 const commit=async()=>{try{await request(`/access-points/import/${job.job_id}/commit?mode=${mode}`,{method:'POST'});setJob(null);await load();}catch(x:any){setError(x.message)}};
 const s=data.summary||{};
 return <div className="ap-sentinel"><div className="ap-title"><div><span><Radio size={15}/> Static wireless inventory</span><h2>Access Point Inventory</h2><p>Controller export reconciled with the latest switch and router CDP/LLDP evidence.</p></div><button onClick={()=>load(data.page)} disabled={loading}><RefreshCw size={16}/>{loading?'Refreshing…':'Refresh Status'}</button></div>{error&&<div className="ap-error"><AlertTriangle size={16}/>{error}</div>}
 <section><h3>Access Point Summary</h3><div className="ap-kpis"><article><Wifi/><span>Total Access Points</span><strong>{s.total||0}</strong></article><article className="good"><Wifi/><span>Online</span><strong>{s.online||0}</strong></article><article className="bad"><WifiOff/><span>Offline</span><strong>{s.offline||0}</strong></article><article><span>Unknown Site</span><strong>{s.unknown_site||0}</strong></article><article><span>Duplicate Serials</span><strong>{s.duplicate_serials||0}</strong></article><article><span>Duplicate MACs</span><strong>{s.duplicate_macs||0}</strong></article></div></section>
 {administrator&&<section className="ap-import"><div className="ap-section-head"><h3>Import Access Points</h3><span>Excel controller export · no LogicMonitor synchronization</span></div><div className="ap-import-controls"><label className="ap-upload"><Upload size={18}/><span>Select .xlsx file</span><input type="file" accept=".xlsx" onChange={e=>validate(e.target.files?.[0])}/></label><label>Import Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="replace">Replace Inventory (Default)</option><option value="merge">Merge Inventory</option></select></label></div>{job&&<div className="ap-preview"><div className="ap-preview-summary"><b>Validation Report</b><span>Total {job.summary.total}</span><span className="ready">Ready {job.summary.ready}</span><span className={job.summary.review?'review':''}>Review {job.summary.review}</span></div><div className="ap-table-wrap"><table><thead><tr><th>Row</th><th>AP Name</th><th>Site</th><th>City</th><th>Model</th><th>Status</th><th>Message</th></tr></thead><tbody>{job.rows.slice(0,100).map((x:any)=><tr key={x.row_number}><td>{x.row_number}</td><td>{x.ap_name}</td><td>{x.site_code}</td><td>{x.city||'Unknown Site'}</td><td>{x.ap_model}</td><td>{x.validation_status}</td><td>{x.validation_message||'Validated'}</td></tr>)}</tbody></table></div><div className="ap-actions"><button className="secondary" onClick={()=>setJob(null)}>Cancel</button><button onClick={commit}>Import {mode==='replace'?'and Replace':'and Merge'}</button></div></div>}</section>}
 <section><div className="ap-section-head"><h3>Access Point Status</h3><span>Calculated from latest CDP/LLDP neighbor evidence</span></div><div className="ap-filters"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/></label><label>Site<input value={site} onChange={e=>setSite(e.target.value.toUpperCase())} placeholder="All"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option>Online</option><option>Offline</option></select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="">All</option>{models.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>load()}>Apply Filters</button></div><div className="ap-table-wrap"><table><thead><tr>{['Status','AP Name','Site Code','City','Province','AP Model','IP Address','Ethernet MAC','Radio MAC','Serial Number','Last Neighbor Detection','Connected Switch','Connected Interface'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id}><td><span className={'ap-status '+x.status.toLowerCase()}>{x.status==='Online'?<CheckCircle2/>:<WifiOff/>}{x.status}</span></td><td><b>{x.ap_name}</b></td><td>{x.site_code}</td><td>{x.city}</td><td>{x.province||'—'}</td><td>{x.ap_model||'—'}</td><td>{x.ip_address||'—'}</td><td>{x.ethernet_mac||'—'}</td><td>{x.radio_mac||'—'}</td><td>{x.serial_number||'—'}</td><td>{x.last_neighbor_detection?new Date(x.last_neighbor_detection).toLocaleString():'—'}</td><td>{x.connected_switch||''}</td><td>{x.connected_interface||''}</td></tr>)}</tbody></table></div>{!data.items.length&&!loading&&<div className="ap-empty"><FileSpreadsheet/><b>No access points imported</b><span>Administrators can import the current controller Excel export above.</span></div>}<div className="ap-pagination" style={{justifyContent:'space-between'}}><label className="ds-pager-size">Show <select value={pageSize} onChange={e=>{const s=Number(e.target.value);setPageSize(s);load(1,s)}}>{[10,20,50,100].map(s=><option key={s} value={s}>{s}</option>)}</select> per page</label><div style={{display:'flex',alignItems:'center',gap:12}}><span>Page {data.page} of {data.pages} · {data.total} total</span><button disabled={data.page<=1} onClick={()=>load(data.page-1)}>Previous</button><button disabled={data.page>=data.pages} onClick={()=>load(data.page+1)}>Next</button></div></div></section>
 {administrator&&history.length>0&&<section><div className="ap-section-head"><h3>Import History</h3><span>Auditable local inventory changes</span></div><div className="ap-table-wrap"><table><thead><tr><th>Import Date</th><th>Imported By</th><th>File</th><th>Records</th><th>Validation Errors</th><th>Mode</th><th>Duration</th><th>Checksum</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{new Date(x.import_date).toLocaleString()}</td><td>{x.imported_by}</td><td>{x.file_name}</td><td>{x.record_count}</td><td>{x.validation_errors}</td><td>{x.import_mode}</td><td>{x.duration_ms} ms</td><td className="checksum">{x.file_checksum}</td></tr>)}</tbody></table></div></section>}</div>
}
