/*
 * helpContent.ts — the single source of truth for the Help Center.
 *
 * Every page, card, KPI and metric in the app is described here in plain English:
 * what it is, why we show it, where the number comes from, the formula/algorithm, a
 * simple example, what is good/bad, and what makes it move. Articles marked with a
 * `live` key get a dynamic "Why this number?" panel filled from GET /help/explain, which
 * reuses the exact same analytics the dashboards use — so Help can never disagree with a
 * page. Tooltips (<Help>) and this registry share the same wording.
 */
export type Article = {
  id: string; cat: string; name: string; synonyms?: string[];
  short: string;            // one line — used in search results and tooltips
  what: string;             // "What is it?"
  why?: string;             // "Why do we show it?"
  from?: string[];          // "Where does the number come from?"
  formula?: string;         // the formula, plainly
  example?: string;         // a kindergarten-simple example
  good?: string;            // what is good / bad
  down?: string;            // what makes it go down
  up?: string;              // what makes it go up
  tech?: string;            // optional technical details for engineers
  related?: string[];       // ids of related articles
  live?: string;            // key handled by the "Why this number?" panel
};

export const CATEGORIES = [
  "Getting Started", "Overview", "Device Fleet", "Network Telemetry", "SLA & Resilience",
  "WAN Providers", "Path Resilience", "Access Points", "Device Details", "Reports",
  "Calculations & Formulas", "Scores & Algorithms", "Thresholds & Colors", "Data Sources",
  "Relationships", "Glossary", "FAQ",
];

export const ARTICLES: Article[] = [
  // ---------------------------------------------------------------- Getting started
  { id: "getting-started", cat: "Getting Started", name: "What this app is",
    synonyms: ["intro", "start", "about"],
    short: "A read-only reliability and SLA report for Medline Canada's network.",
    what: "This app shows how healthy and reliable Medline Canada's Cisco network is. It reads data from LogicMonitor (the monitoring system) and turns it into simple executive numbers.",
    why: "So leadership can see one clear picture of network reliability — a real SLA number, where the risk is, and what to act on — without trusting a hand-made spreadsheet.",
    from: ["LogicMonitor monitoring data (read-only)", "The app's own database of daily results"],
    good: "Two rules shape everything: (1) the app never changes anything on LogicMonitor or the devices; (2) if there isn't enough evidence for a number, it shows \"Insufficient evidence\" instead of guessing a fake 0% or 100%.",
    related: ["overview", "data-sources", "availability", "sla"] },
  { id: "reading-numbers", cat: "Getting Started", name: "How to read a number",
    synonyms: ["why this number", "explain", "trust"],
    short: "Point at any number and ask what it means, where it's from, and why it's that value.",
    what: "Every meaningful number in the app can be explained: what it is, where it comes from, how it's calculated, and why it currently has that value.",
    why: "So you never have to guess. If two pages show slightly different numbers, it's usually because of the time period or rounding — both explained here.",
    good: "Look for the (i) icon next to a section for a quick tooltip, and open this Help Center for the full story and the live \"Why this number?\" panel.",
    related: ["rounding", "time-periods", "insufficient-evidence"] },

  // ---------------------------------------------------------------- Overview
  { id: "overview", cat: "Overview", name: "Overview page", synonyms: ["executive", "dashboard", "command center", "home"],
    short: "The executive landing page — one screen for network health.",
    what: "The Overview is the leadership home page. It shows the overall SLA, how devices are split by importance, the last 7 days, which devices need attention, what to act on, and each site's reliability.",
    why: "It answers 'is the network healthy?' in a few seconds.",
    from: ["Only devices in Device Fleet are counted — never the whole LogicMonitor account.", "All numbers are read from stored daily results, so the page is fast and matches the other pages."],
    good: "Everything here is fleet-scoped and drawn from saved evidence. Nothing is a live guess.",
    related: ["global-sla", "criticality", "seven-day", "site-reliability", "business-units", "leadership-actions"] },
  { id: "global-sla", cat: "Overview", name: "Global SLA Status", synonyms: ["global status", "network sla", "overall health", "99%"],
    short: "The overall network availability over the last 30 days, versus the target.",
    what: "Global SLA Status is the network's overall availability over the trailing 30 days. It is shown as a percentage next to the target.",
    why: "It gives leadership one number for 'how available was the network lately'.",
    from: ["The daily up/observed minutes of every monitored Fleet device, for the last 30 days."],
    formula: "Availability = up minutes ÷ observed minutes × 100, combined across all devices.",
    example: "If the network was up for 43,187 of every 43,200 observed minutes, availability = 43,187 ÷ 43,200 × 100 = 99.97%.",
    good: "At or above the target (99.9%) = Target met. Just under = At risk. Well under = Below target.",
    down: "A device going offline, a site losing connectivity, or packet loss reaching 100% on a device for a while.",
    up: "Devices staying reachable with low packet loss across the 30 days.",
    tech: "Coverage-gated at 90%: if less than 90% of the expected minutes were actually observed, no number is published (shown as Insufficient evidence). Measured in the America/Vancouver timezone from the sla_daily rollup.",
    related: ["availability", "coverage", "sla", "seven-day", "site-reliability"], live: "global_sla" },
  { id: "criticality", cat: "Overview", name: "Device Criticality", synonyms: ["criticality", "critical high medium low", "device count", "donut"],
    short: "All Fleet devices split by how important they are (Critical / High / Medium / Low).",
    what: "This donut shows every device in the Fleet grouped by business importance. The centre shows the total number of devices.",
    why: "So you can see how much of the network is business-critical, and how many important devices are unhealthy.",
    from: ["The importance you set per device in Settings.", "The current status of each device (from its latest collection)."],
    example: "40 devices might be 12 Critical, 15 High, 10 Medium, and 3 Low.",
    good: "'Degraded' and 'Unreachable' counts flag how many devices currently need attention.",
    tech: "The count is the logical device count (one row per device). Site and business-unit tables count physical switches, which is higher because one logical device can be a stack of several switches.",
    related: ["device-fleet", "physical-count", "core-infra"], live: "criticality" },
  { id: "seven-day", cat: "Overview", name: "7-Day Availability", synonyms: ["7 day", "week bars", "daily availability"],
    short: "Availability for each of the last 7 days.",
    what: "One bar per day for the last week, showing that day's network availability. A red bar means that day was below the target.",
    why: "To spot a bad day quickly and see the recent trend.",
    from: ["The stored daily availability for the Fleet, per day."],
    good: "All bars near 100% is healthy. A red bar points to a day worth investigating.",
    related: ["global-sla", "availability"] },
  { id: "throughput", cat: "Overview", name: "Snapshot Utilisation (instant)", synonyms: ["throughput", "traffic", "gbps", "bandwidth", "aggregate throughput", "utilisation"],
    short: "Traffic flowing at the single moment of the last poll — not an average or a peak.",
    what: "A point-in-time estimate of how much traffic was crossing all monitored, working interfaces at the instant the app last collected data.",
    why: "A quick 'what is happening right now' indicator. It is deliberately NOT the headline capacity number, because one instant is not representative of a working day.",
    from: ["Each up interface's speed and how busy it was (in % + out %) at the last poll, added together."],
    formula: "Snapshot utilisation = sum of (interface speed × (in% + out%)) over every up interface, at one moment.",
    example: "A 1 Gbps link 2% busy inbound and 1% busy outbound contributes 1,000,000,000 × 3% = 30 Mbps.",
    good: "Because office traffic is bursty and links are large, this number is usually very low (well under 1% of total capacity) and will swing between polls. That is expected, not a fault. For the number that actually answers 'how loaded does the network get', use Fleet Throughput on the Path Resilience page (busy-hour peak / average / 95th percentile).",
    tech: "Counts both directions (in + out). It is a gross fleet total across access and uplink interfaces, so inter-switch links are counted at both ends; it is not a WAN-egress or billing figure.",
    related: ["fleet-throughput", "interface-util", "network-telemetry"] },
  { id: "core-infra", cat: "Overview", name: "Core Infrastructure Health", synonyms: ["core", "attention", "worst devices"],
    short: "The devices most needing attention, ranked by severity × importance.",
    what: "A short list of the devices that most need attention right now. Click a row to open that device.",
    why: "So you act on the highest-impact problems first.",
    from: ["Each device's current problem (unreachable, high CPU/memory/temperature, hardware fault) combined with its business importance."],
    good: "A device high on this list means a real problem on an important device.",
    related: ["criticality", "leadership-actions", "device-detail"] },
  { id: "leadership-actions", cat: "Overview", name: "What leadership can act on now", synonyms: ["actions", "recommendations", "priorities", "risks"],
    short: "The top prioritised actions (P1/P2/P3) with a recommended next step.",
    what: "A short, prioritised list of what to fix, in business-impact order. Each item has a plain recommended action.",
    why: "It turns raw problems into decisions.",
    from: ["Unreachable or critical devices, capacity risks (CPU/memory/temperature), sites with several impaired devices at once, single-point-of-failure exposure, unmapped devices, and fleet SLA below target."],
    good: "P1 = urgent, P2 = important, P3 = housekeeping. If the list is empty, the network is within targets.",
    related: ["core-infra", "resilience", "recommendations"] },
  { id: "business-units", cat: "Overview", name: "Business Unit Reliability", synonyms: ["business unit", "healthcare", "dental", "rollup"],
    short: "The fleet rolled up by business unit (e.g. Healthcare vs Dental).",
    what: "Reliability grouped by business unit. Each card shows YTD and 30-day availability, device count, sites, and open incidents for that unit.",
    why: "So each part of the business can see its own network reliability.",
    from: ["The business unit set on each site, plus that unit's devices' daily availability."],
    good: "YTD is measured from when each site was first monitored. A site added mid-year shows a real number plus a 'since <month>' note — not a blank.",
    tech: "Device counts are physical switches (stack-aware). 'Insufficient' only appears when a unit genuinely has too little evidence; a new project shows the reason instead.",
    related: ["site-reliability", "coverage", "commissioning"], live: "business_units" },
  { id: "site-reliability", cat: "Overview", name: "Site Reliability", synonyms: ["site health", "per site", "branch"],
    short: "Per-site availability (YTD & 30-day), device health, incidents and status.",
    what: "A table with one row per site: its YTD and 30-day availability, number of devices, device health, incidents, and overall status.",
    why: "So you can see which locations are strong and which need attention.",
    from: ["Each site's devices' daily availability and current status."],
    good: "Green status = healthy. A site can show a real YTD with a 'since <month>' note if it was commissioned mid-year.",
    down: "A device at the site going offline, or the site's availability dropping below target.",
    tech: "Devices column counts physical switches (stack members included). Coverage-gated per site.",
    related: ["business-units", "commissioning", "physical-count"], live: "worst_site" },

  // ---------------------------------------------------------------- Device Fleet
  { id: "device-fleet", cat: "Device Fleet", name: "Device Fleet page", synonyms: ["fleet", "inventory", "switches", "devices"],
    short: "The operational list of switches and routers, with SLA compliance.",
    what: "The Device Fleet is the working list of every switch and router the app watches, with a summary, a compliance trend, and each device's uptime and availability.",
    why: "It is the operational view for engineers — the source of the fleet scope everything else uses.",
    from: ["The app's inventory of devices, joined with their collected LogicMonitor data."],
    related: ["fleet-summary", "compliance-trend", "device-detail", "physical-count"] },
  { id: "fleet-summary", cat: "Device Fleet", name: "Fleet Summary", synonyms: ["total devices", "below sla", "monitoring gaps"],
    short: "Totals: physical switches, valid uptime, YTD availability, below-SLA, gaps, errors.",
    what: "The KPI row at the top of Device Fleet: total physical switches, how many have valid uptime, fleet YTD availability, how many are below SLA, monitoring gaps, and collection errors.",
    why: "A quick health summary of the whole fleet.",
    from: ["The device inventory and the daily availability rollup."],
    tech: "Total Network Devices counts physical switches including stack members (APs excluded) — this is normally larger than the logical device count on the Overview donut.",
    related: ["physical-count", "criticality"] },
  { id: "compliance-trend", cat: "Device Fleet", name: "Compliance Trends", synonyms: ["trend chart", "12 weeks", "downtime bars"],
    short: "A 12-week combo chart: availability line, downtime bars, and the SLA target.",
    what: "A chart of the last 12 weeks. The blue line is weekly availability, the orange bars are weekly downtime minutes, and the dashed amber line is the SLA target. Bars spike where the line dips.",
    why: "To see whether reliability is improving or worsening over time.",
    from: ["The weekly totals of up/observed/down minutes across the Fleet."],
    good: "A rising line and shrinking bars are good. It also shows week-over-week and month-over-month direction.",
    related: ["seven-day", "trend-intel", "availability"] },
  { id: "physical-count", cat: "Device Fleet", name: "Switches vs monitored units (stacks)", synonyms: ["stack", "chassis", "number of switches", "monitored", "devices", "why two numbers"],
    short: "A stack is several physical switches that monitoring sees as one device — both numbers are correct.",
    what: "Switches are often 'stacked': several physical boxes cabled together so they behave as a single switch. Monitoring polls that stack once, as ONE device. So a branch can honestly have 28 physical switches while monitoring lists 10 units.",
    why: "Both numbers answer different, legitimate questions. 'How much hardware do we own and support?' is the physical count. 'How many things is monitoring watching?' is the unit count. Quoting only one of them causes arguments.",
    from: ["The collected hardware inventory: chassis serial numbers, falling back to stack-port member evidence."],
    formula: "Physical switches = sum of chassis across every unit. Monitored units = number of logical devices LogicMonitor polls.",
    example: "CA15 Guelph has 10 monitored units. All 10 are stacks, totalling 28 physical switches — one of them (CA15-Z01-ASW-01) is a 6-switch stack on its own.",
    good: "A monitored-unit count lower than the switch count means STACKED, not unmonitored. If a device were genuinely unmonitored it would appear as a monitoring gap on Device Fleet, not as a difference between these two numbers.",
    tech: "Every enabled device in inventory is currently mapped to LogicMonitor and actively collected — there are no unmapped or disabled devices in the fleet, so 'all monitored' is literal.",
    related: ["criticality", "site-reliability", "fleet-summary", "monitoring-gaps", "path-resilience"] },

  // ---------------------------------------------------------------- Network Telemetry
  { id: "network-telemetry", cat: "Network Telemetry", name: "Network Telemetry page", synonyms: ["telemetry", "measurements", "live data"],
    short: "What the network is doing — latency, loss, interfaces, routing, and coverage.",
    what: "This page shows measurements collected from routers and switches: delay, packet loss, interface health, routing adjacencies, and an honest matrix of what the monitoring system can actually see.",
    why: "To understand network behaviour and its limits.",
    from: ["LogicMonitor datasources (Ping, interfaces, OSPF, etc.)."],
    related: ["latency", "packet-loss", "jitter", "interface-util", "data-coverage", "routing"] },
  { id: "latency", cat: "Network Telemetry", name: "Latency", synonyms: ["delay", "response time", "rtt", "ms"],
    short: "How long a packet takes to travel and get a reply. Lower is better.",
    what: "Latency is the delay for a packet to reach a device and come back, in milliseconds (ms).",
    why: "High delay makes apps and calls feel slow.",
    from: ["LogicMonitor's Ping datasource (round-trip time)."],
    formula: "Average latency = sum of response times ÷ number of responses.",
    good: "On a LAN, single-digit ms is normal. Tens of ms is fine for most WAN links. Sustained high values need investigation.",
    related: ["packet-loss", "jitter"], live: "latency" },
  { id: "packet-loss", cat: "Network Telemetry", name: "Packet Loss", synonyms: ["loss", "dropped packets", "lost"],
    short: "How much traffic did not arrive. 0% is best.",
    what: "Packet loss is the share of packets that did not make it. It is a percentage.",
    why: "Loss causes retries, slowness, and dropped calls.",
    from: ["LogicMonitor's Ping datasource."],
    formula: "Packet loss % = lost packets ÷ sent packets × 100.",
    example: "5 lost out of 1,000 sent = 5 ÷ 1,000 × 100 = 0.5%.",
    good: "0% is ideal. A small amount can be normal. Steady loss above ~1–2% needs attention.",
    tech: "This is also how availability is judged: a device is counted 'up' for a minute when packet loss is below 100% (it answered at least one probe).",
    related: ["latency", "availability"], live: "loss" },
  { id: "jitter", cat: "Network Telemetry", name: "Jitter", synonyms: ["jitter", "delay variation"],
    short: "How much the delay changes. Steady delay is better.",
    what: "Jitter is how much the delay varies from packet to packet. Steady delay is better than delay that jumps around.",
    why: "Voice and video need steady delay to sound and look smooth.",
    good: "Lower jitter is better.",
    tech: "Jitter is Not monitored for this fleet — the Cisco IP-SLA jitter datasource has no instances. The app shows 'Not monitored' rather than a fake value.",
    related: ["latency", "data-coverage"] },
  { id: "interface-util", cat: "Network Telemetry", name: "Interface Utilisation", synonyms: ["utilisation", "bandwidth", "busy", "high util"],
    short: "How much of an interface's capacity is being used.",
    what: "Interface utilisation is how busy a network connection is, as a share of its total capacity.",
    why: "A link near 100% for long periods causes congestion and drops.",
    from: ["LogicMonitor's interface datasource (in/out utilisation)."],
    good: "Well under 80% is comfortable. Sustained above ~80% is flagged as high utilisation.",
    related: ["interfaces-table", "throughput"], live: "interfaces" },
  { id: "data-coverage", cat: "Network Telemetry", name: "Data Coverage", synonyms: ["coverage matrix", "not monitored", "what is monitored"],
    short: "An honest list of what LogicMonitor can and cannot see for this fleet.",
    what: "A table that says, per metric, whether it is Monitored, Partial, Not monitored, or Not available — with the datasource and device count.",
    why: "So you know why some sections show 'not monitored' instead of a number.",
    good: "Availability, latency, CPU, memory, interfaces and topology are Monitored. OSPF is Partial. BGP, EIGRP, static routes and jitter are Not monitored in this tenant.",
    related: ["routing", "jitter"] },

  // ---------------------------------------------------------------- Routing
  { id: "routing", cat: "Network Telemetry", name: "Routing Health (OSPF)", synonyms: ["routing", "ospf", "adjacency", "neighbors"],
    short: "OSPF neighbour adjacencies per device. BGP/EIGRP/static are not monitored here.",
    what: "Shows OSPF routing adjacencies per device: how many are Full versus total, and neighbour events.",
    why: "Routing decides how traffic finds its path. A lost adjacency can reroute or black-hole traffic.",
    from: ["LogicMonitor's OSPF_Neighbors datasource (only on OSPF-enabled devices)."],
    good: "Full adjacency = healthy. BGP, EIGRP and static routes are Not monitored in this tenant (no instances), so they are shown as such — not as zero.",
    related: ["bgp", "ospf", "static-routes", "data-coverage"], live: "routing" },
  { id: "ospf", cat: "Network Telemetry", name: "OSPF", synonyms: ["ospf", "open shortest path first"],
    short: "A routing protocol that helps routers find paths inside a network.",
    what: "OSPF is a routing protocol. Routers use it to learn the best paths inside the network and to notice when a link fails.",
    why: "It keeps traffic flowing on the best available internal path.",
    good: "A 'Full' neighbour state is healthy. This is the one routing protocol monitored for the Medline fleet.",
    related: ["routing", "bgp", "static-routes"] },
  { id: "bgp", cat: "Network Telemetry", name: "BGP", synonyms: ["bgp", "border gateway protocol", "peer"],
    short: "A routing protocol routers use to exchange available paths, often with providers.",
    what: "BGP is a routing protocol. Routers use it to tell each other which network paths are available, often between your network and a provider.",
    why: "A BGP session failure can remove a path and reduce redundancy.",
    good: "On the company switches, BGP is Not monitored (no instances). On the WAN Providers' routers, BGP peers are monitored and shown.",
    related: ["routing", "wan-providers", "resilience"] },
  { id: "static-routes", cat: "Network Telemetry", name: "Static Routes", synonyms: ["static route", "manual route"],
    short: "A path configured by hand instead of learned automatically.",
    what: "A static route is a network path set manually by an engineer, rather than learned by a protocol like OSPF or BGP.",
    why: "Static routes are simple but do not automatically reroute if the path fails.",
    good: "Static route counts are Not monitored in this tenant (no datasource), so they are shown as 'Not monitored', not zero.",
    related: ["routing", "ospf", "bgp"] },

  // ---------------------------------------------------------------- SLA & Resilience
  { id: "sla", cat: "SLA & Resilience", name: "SLA", synonyms: ["service level agreement", "compliance", "target"],
    short: "The service level we expect, e.g. 99.9% availability.",
    what: "SLA means Service Level Agreement — the level of service we expect. For example, a target availability of 99.9%.",
    why: "It sets the bar. If actual availability meets the target, the SLA passed; if not, it failed.",
    example: "Target 99.9%. Actual 99.95% → passed. Actual 99.50% → failed.",
    good: "The default target is 99.9% (configurable).",
    related: ["global-sla", "availability", "coverage", "uptime-tier"] },
  { id: "availability", cat: "SLA & Resilience", name: "Availability", synonyms: ["available", "uptime %", "service availability"],
    short: "How much of the monitored time the service was working.",
    what: "Availability is the share of monitored time a device or the network was working (answering probes).",
    why: "It is the core reliability number and the basis of the SLA.",
    from: ["The device's up minutes and observed minutes, from the Ping datasource, rolled up daily."],
    formula: "Availability % = up minutes ÷ observed minutes × 100.",
    example: "Up 718 hours out of 720 observed → 718 ÷ 720 × 100 = 99.72%.",
    good: "99.99–100% Excellent · 99.9–99.99% Very good · 99–99.9% Acceptable · below 99% Needs attention.",
    tech: "A minute counts as 'up' when packet loss is below 100%. Coverage-gated at 90%. Availability is not the same as device uptime — see 'Uptime vs Availability'.",
    related: ["coverage", "uptime-vs-avail", "reliability", "sla"], live: "global_sla" },
  { id: "coverage", cat: "SLA & Resilience", name: "Coverage (evidence)", synonyms: ["coverage", "evidence", "insufficient"],
    short: "How much of the expected time we actually have data for.",
    what: "Coverage is the share of the expected minutes we actually observed. It tells us how much evidence a number is based on.",
    why: "A number based on little data can mislead. So the app hides availability when coverage is too low.",
    formula: "Coverage % = observed minutes ÷ expected minutes × 100.",
    good: "At or above 90% = enough evidence to publish. Below 90% = shown as 'Insufficient evidence' rather than a fake number.",
    tech: "Coverage is commissioning-aware: a device is measured from when it was first observed, so a site added mid-year is not penalised for months it did not exist.",
    related: ["insufficient-evidence", "commissioning", "availability"] },
  { id: "insufficient-evidence", cat: "SLA & Resilience", name: "Insufficient evidence", synonyms: ["insufficient", "no data", "not enough"],
    short: "Not enough monitoring data to publish a trustworthy number.",
    what: "'Insufficient evidence' means the app didn't observe enough of the time period to give a trustworthy availability number.",
    why: "It is more honest than showing a made-up 0% or 100%.",
    good: "It is never treated as 0%. Once enough data is collected, a real number appears.",
    related: ["coverage", "commissioning"] },
  { id: "commissioning", cat: "SLA & Resilience", name: "Commissioning-aware YTD", synonyms: ["since", "new site", "mid year", "commissioned"],
    short: "A site is measured from when it was first monitored, so new projects aren't penalised.",
    what: "Year-to-date availability is measured from the day each site was first monitored — not from January 1 if it didn't exist yet.",
    why: "A site added in June would look terrible if measured from January. This shows its real availability with a 'since <month>' note instead.",
    example: "A site first seen in June shows 'since Jun 2026' and a normal availability, not 'Insufficient'.",
    related: ["coverage", "business-units", "site-reliability"] },
  { id: "reliability", cat: "SLA & Resilience", name: "Reliability", synonyms: ["reliability", "mtbf", "how often fail"],
    short: "How often something fails — not just whether it was working.",
    what: "Availability asks 'was it working?'. Reliability asks 'how often did it fail?'. A device can be highly available but still fail often for short moments.",
    why: "Frequent small failures are a warning sign even when availability looks high.",
    example: "A device fails 10 times, each for 10 seconds. Availability is still very high, but reliability is worse because it failed many times.",
    tech: "The app derives incidents and MTTR/MTBF from availability history (contiguous below-100% days). Exact per-second timings would require LogicMonitor alert history.",
    related: ["availability", "mttr-mtbf", "incidents"] },
  { id: "resilience", cat: "SLA & Resilience", name: "Resilience (tier estimate)", synonyms: ["resilience", "tier", "redundancy", "uptime institute"],
    short: "How well the network keeps working when something fails.",
    what: "Resilience is about surviving failure. The app awards Tier I or Tier II only from directly observed component evidence (a stack or dual power). Tier III/IV require independently verified failure domains and are never inferred from neighbour names or availability.",
    why: "High availability today doesn't help if one failure takes a site down. Resilience shows that exposure.",
    from: ["Observed redundancy signals per device, combined with measured availability. Reassessed every 12 hours."],
    good: "Tier II means observed N+1 component evidence. Tier III/IV remain unclaimed until an engineer verifies independent end-to-end paths and failure domains. The fleet tier is limited by its weakest critical node.",
    tech: "This is a network-redundancy estimate mapped onto Uptime Institute bands, not a facility (power/cooling) certification. Availability is reported as context; it does not prove fault tolerance.",
    related: ["uptime-tier", "bgp", "leadership-actions"], live: "resilience" },
  { id: "uptime-tier", cat: "SLA & Resilience", name: "Uptime tier comparison", synonyms: ["tier", "budget", "annual downtime"],
    short: "Measured availability compared to the Uptime Institute tier budgets.",
    what: "A table comparing the fleet's measured availability to the Uptime Institute availability budgets (Tier I 99.671% up to Tier IV 99.995%). The highlighted row is the estimated band.",
    why: "It puts our availability in an industry frame.",
    good: "Higher tier = less allowed annual downtime. These tiers certify facility power/cooling; here we use them only as an availability yardstick.",
    related: ["resilience", "availability"] },
  { id: "mttr-mtbf", cat: "SLA & Resilience", name: "MTTR & MTBF", synonyms: ["mttr", "mtbf", "mean time"],
    short: "Average time to recover, and average time between failures.",
    what: "MTTR is the average time to recover from an incident. MTBF is the average time between failures.",
    why: "Short MTTR and long MTBF mean a healthy, quick-to-recover network.",
    formula: "MTTR = total repair time ÷ number of incidents. MTBF = total operating time ÷ number of failures.",
    good: "Lower MTTR is better. Higher MTBF is better.",
    tech: "Both are approximate and availability-derived (from the daily rollup), not from a discrete alert log.",
    related: ["incidents", "reliability"], live: "incidents" },
  { id: "incidents", cat: "SLA & Resilience", name: "Incidents", synonyms: ["incidents", "outages", "downtime events"],
    short: "Runs of below-100% availability days, treated as incidents.",
    what: "An incident is a run of consecutive days where a device's availability was below 100% (with enough evidence). The table lists the largest ones.",
    why: "To see the biggest downtime events and where they happened.",
    from: ["The daily availability rollup, over the last 90 days."],
    good: "Fewer and shorter incidents are better.",
    tech: "Availability-derived and coverage-gated — approximate, not exact start/stop times.",
    related: ["mttr-mtbf", "reliability", "alerts"], live: "incidents" },
  { id: "trend-intel", cat: "SLA & Resilience", name: "Trend intelligence", synonyms: ["trend", "wow", "mom", "improving", "worsening"],
    short: "Week-over-week and month-over-month direction (improving / worsening).",
    what: "Shows whether availability is improving or worsening compared to the previous week and the previous month.",
    why: "Direction matters as much as the current number.",
    good: "IMPROVING is good, WORSENING needs attention, UNCHANGED is steady.",
    related: ["compliance-trend", "mttr-mtbf"], live: "trends" },
  { id: "uptime-vs-avail", cat: "SLA & Resilience", name: "Uptime vs Availability", synonyms: ["uptime", "difference"],
    short: "Uptime is how long a device ran; availability is how reachable the service was.",
    what: "Device uptime is how long the device has run since its last restart. Availability is how much of the monitored time the service was actually reachable. They are different.",
    why: "A device can have long uptime but poor availability (e.g. it was up but unreachable), or short uptime but high availability (a quick reboot).",
    related: ["availability", "health-data"] },

  // ---------------------------------------------------------------- WAN Providers
  { id: "wan-providers", cat: "WAN Providers", name: "WAN Providers page", synonyms: ["wan", "carrier", "centrilogic", "provider routers"],
    short: "The carriers' own routers — shown for visibility, never counted in Medline metrics.",
    what: "A separate page for the WAN providers' routers (e.g. Centrilogic circuits). It shows their status, reachability, BGP/OSPF, and interfaces.",
    why: "For visibility into the provider edge — but these devices are NOT Medline's, so they are kept completely out of the company's SLA, Overview and reports.",
    from: ["LogicMonitor (read-only), stored in a separate table that never mixes with the Fleet."],
    good: "Numbers here are descriptive counts only (routers, established BGP peers, full OSPF). No SLA is scored against Medline.",
    related: ["bgp", "routing", "path-resilience"] },

  // ---------------------------------------------------------------- Path Resilience
  { id: "path-resilience", cat: "Path Resilience", name: "Path Resilience page", synonyms: ["path resilience", "failover", "redundancy", "branch resilience"],
    short: "Per branch: can it survive a failure, and what would it fall back to?",
    what: "Every other page answers 'was it working?'. This page answers a different question: 'if something breaks, does the branch keep working?' For each branch it shows how redundant the design actually is, which provider circuits serve it, which route it uses to get out, and what to fix.",
    why: "Availability tells you the past. Resilience tells you the risk. A branch can show 100% uptime all year and still be one cable away from a full outage — leadership needs to see that before it happens, not after.",
    from: ["LogicMonitor (stack members, neighbours, interface state, circuit status)", "The app's daily availability history", "Optional read-only SSH collection from the branch's distribution switch for routing detail"],
    good: "Nothing on this page is guessed. Where the routing data has not been collected yet, the page says so plainly instead of assuming the branch is fine.",
    related: ["branch-posture", "best-path-availability", "wan-circuits", "priority-routes", "fleet-throughput", "ccie-kb"] },

  { id: "branch-posture", cat: "Path Resilience", name: "Failover posture", synonyms: ["posture", "fully redundant", "single l3 default", "east-west"],
    short: "A one-line verdict on whether the branch can survive a failure.",
    what: "A plain-English label summarising the branch's redundancy: whether the distribution switch is stacked, whether access switches have two uplinks, and whether there is more than one way out to the wider network.",
    why: "So a non-technical reader can sort branches by risk without reading a topology diagram.",
    formula: "Fully redundant = stacked distribution AND dual-homed access AND (more than one exit path OR two or more provider circuits). Otherwise the label states exactly which part is missing.",
    example: "'Redundant east-west, single L3 default' means: inside the building everything has a backup, but there is only one route out — so a failure upstream still isolates the site.",
    good: "'Fully redundant' is good. Any label mentioning 'single' is a single point of failure worth a conversation.",
    tech: "East-west redundancy comes from LogicMonitor stack evidence and CDP/LLDP neighbour counts. Northbound redundancy needs the routing table, which only SSH collection can provide.",
    related: ["path-resilience", "priority-routes", "wan-circuits", "resilience"] },

  { id: "best-path-availability", cat: "Path Resilience", name: "Best-path vs pooled availability", synonyms: ["best path", "pooled", "redundancy aware"],
    short: "Two honest views: did the branch keep a path, and how did every device do.",
    what: "Each availability tile shows two numbers. Best-path asks 'did the branch keep at least one working path?' — the redundancy-aware view. Pooled asks 'how did every device do on average?' — the strict view.",
    why: "If a backup switch carries the site while one device reboots, the branch never actually lost service. Best-path reflects what users experienced; pooled reflects the equipment's own record. Showing only one of them would mislead.",
    formula: "Pooled = total up minutes ÷ total observed minutes across every device in the branch. Best-path = the availability of the branch's best-covered device for that window.",
    example: "One of ten switches is down for an hour but the site stays online: pooled dips slightly, best-path stays 100%.",
    good: "A large gap between the two means the branch is leaning on its redundancy — worth investigating which device keeps failing, even though users felt nothing.",
    tech: "Both are computed from the same daily rollup rows used everywhere else, so they always reconcile with the SLA page and the reports.",
    related: ["availability", "path-resilience", "time-periods"] },

  { id: "wan-circuits", cat: "Path Resilience", name: "WAN circuits (providers)", synonyms: ["circuits", "carrier", "primary", "backup", "bell", "telus"],
    short: "Which provider links serve the branch, and which one is actually carrying traffic.",
    what: "The provider circuits mapped to each branch, with the one currently used as the default route marked as primary (①).",
    why: "Carrier diversity is the difference between a provider outage being an inconvenience and being a site outage. This makes it visible per branch.",
    from: ["The WAN Providers inventory, matched to the branch by the transit network its distribution switch sits on and by the route it actually uses."],
    good: "Two or more circuits from different carriers is good. One circuit means a single carrier failure takes the branch offline.",
    tech: "Important nuance: having two circuits physically present does NOT mean failover works. If the switch has only one default route and no gateway redundancy, the backup circuit will not be used automatically — the page flags exactly that case and the recommended fix.",
    related: ["path-resilience", "priority-routes", "wan-providers", "branch-posture"] },

  { id: "priority-routes", cat: "Path Resilience", name: "Priority routes (best route)", synonyms: ["default gateway", "priority", "next hop", "best route", "routing"],
    short: "The order the branch would try its exits — first choice, second, third.",
    what: "The branch's default routes ranked ①②③ by which one the switch prefers, showing the next hop it sends traffic to and how strongly it prefers it.",
    why: "This is the actual failover plan as configured on the equipment — not what the design document says it should be.",
    from: ["The distribution switch's routing table, collected read-only over SSH."],
    formula: "Ranked by administrative distance first, then metric — exactly how the switch itself decides.",
    example: "A second default route with a much higher administrative distance is a 'floating' backup: it sits unused and only takes over if the first one disappears.",
    good: "Two or more entries means a configured fallback. A single entry means there is no automatic second choice, no matter how many circuits are physically installed.",
    tech: "LogicMonitor does not expose routing tables for this tenant, so this section stays empty until an administrator runs the SSH collection for that branch. Empty means 'not collected', never 'no backup exists'.",
    related: ["wan-circuits", "branch-posture", "ssh-gapfill", "static-routes"] },

  { id: "fleet-throughput", cat: "Path Resilience", name: "Fleet throughput (average / busy-hour peak / p95)", synonyms: ["busy hour", "peak", "95th percentile", "p95", "load", "capacity"],
    short: "How loaded the network actually gets over a week — not a single instant.",
    what: "Traffic across the whole fleet measured hour by hour over the last 7 days, summarised three ways: the typical level (average), the busiest single hour (peak), and the level only exceeded 5% of the time (95th percentile).",
    why: "Capacity decisions need the busy hour, not a random moment. A single instantaneous reading taken at lunchtime says nothing about the 9am peak.",
    from: ["The app's own stored history of interface readings, bucketed by hour. No extra load is placed on the monitoring system to produce it."],
    formula: "For each hour, sum (interface speed × (in% + out%)) across all up interfaces. Average = mean of those hours. Busy-hour peak = the largest. 95th percentile = the value only 5% of hours exceed.",
    example: "Average 1.5 Gbps with a 9 Gbps busy-hour peak means the network is quiet most of the time but has real spikes — size for the spike, not the average.",
    good: "The 95th percentile is the fairest 'normal busy' figure because it ignores one-off spikes; it is the same method carriers use for billing.",
    tech: "Both directions are counted (in + out). It is a fleet-wide gross total, so links between switches are counted at both ends; a WAN-egress-only split needs interface classification that is not collected yet.",
    related: ["throughput", "interface-util", "path-resilience"] },

  { id: "ccie-kb", cat: "Path Resilience", name: "Recommended remediation (CCIE KB)", synonyms: ["remediation", "recommendation", "fix", "kb", "commands"],
    short: "For each risk found, the recommended fix and the exact commands to verify it.",
    what: "When the page finds a resilience gap, it attaches a plain-English explanation of why it matters, the recommended remedy, and copy-ready commands an engineer can run to check or apply it.",
    why: "A finding without a fix is just a complaint. This turns each risk into an actionable work item that a network engineer can act on directly.",
    good: "The commands are read-only checks and configuration suggestions for a human to review — the app never runs them or changes any device itself.",
    tech: "Recommendations are matched to the specific evidence found (for example: backup circuit present but unused by routing → tracked floating static route). Each entry cites the internal Cisco CLI reference section it derives from.",
    related: ["branch-posture", "priority-routes", "wan-circuits"] },

  { id: "alert-runbooks", cat: "Device Details", name: "Alert remediation runbooks (administrators)", synonyms: ["syslog", "alert", "procedure", "command", "ccie", "fix"],
    short: "Every actionable SSH alert has its cause, procedure, safe verification commands and Cisco reference.",
    what: "Administrators see a remediation row for every collected Emergency, Alert, Critical, Error or Warning syslog event. It includes the parsed cause, a change-safe procedure, read-only verification commands and a Cisco IOS XE reference. Unknown mnemonics receive a generic triage procedure rather than being silently ignored.",
    why: "A severity colour tells you urgency; a runbook tells you how to investigate safely and prove the issue is resolved.",
    good: "Commands are for a qualified engineer to run in an approved session. The app never runs commands, pushes configuration, stores passwords, or clears counters.",
    tech: "Critical/Alert/Emergency events are P1; Error is P2; Warning is P3. Read-only viewers do not receive remediation rows, procedures or CLI in their API response.",
    related: ["alerts", "ssh-gapfill", "ccie-kb"] },

  { id: "vlan-port-evidence", cat: "Device Details", name: "VLAN and port evidence", synonyms: ["vlan", "port", "access port", "trunk", "interface vlan"],
    short: "Interface VLANs are linked only from explicit collected membership evidence.",
    what: "The Interfaces table uses the device's collected VLAN membership to label a port when the port appears unambiguously in that VLAN's access-port list. SVIs such as Vlan10 also identify their own VLAN.",
    why: "A description such as 'Users' is not proof of VLAN membership. Showing it as a VLAN would be fabricated data.",
    good: "Access-port VLAN shown = directly collected evidence. Trunks and ambiguous ports remain Not available until their detailed configuration is collected.",
    related: ["interfaces-table", "ssh-gapfill"] },

  { id: "topology-port-evidence", cat: "Device Details", name: "Topology port labels", synonyms: ["topology", "cdp", "lldp", "local port", "remote port"],
    short: "The topology labels verified local and, when supplied, remote interfaces.",
    what: "Each topology link shows the local interface from CDP/LLDP. A remote interface is shown only if the collected neighbour data provides a real port value; monitoring placeholders are intentionally hidden.",
    why: "A diagram without ports is hard to troubleshoot; inventing the far-end port is worse.",
    related: ["cdp-lldp", "vlan-port-evidence"] },

  { id: "branch-ssh-pull", cat: "Path Resilience", name: "Pull via SSH (administrators)", synonyms: ["ssh", "pull", "collect", "fill gaps"],
    short: "How the routing detail gets collected for a branch.",
    what: "An administrator-only button that shows the exact read-only commands to run on the branch's distribution switch, and accepts the pasted output to fill in the routing, gateway-redundancy and link-bundle detail.",
    why: "LogicMonitor cannot see routing tables for this tenant, so this is the only way to know a branch's real failover configuration.",
    good: "It is strictly read-only ('show' commands). The app stores the results and never sends any configuration to a device. Device passwords are never stored.",
    tech: "Visible to administrators only. Read-only viewers can see everything the page has already collected, but cannot trigger a collection.",
    related: ["ssh-gapfill", "priority-routes", "path-resilience"] },

  // ---------------------------------------------------------------- Access Points
  { id: "access-points", cat: "Access Points", name: "Access Points page", synonyms: ["ap", "wifi", "9120", "9130", "wireless"],
    short: "The Cisco Wi-Fi access points, with Online/Offline status inferred every ~2 hours.",
    what: "The list of Cisco 9120/9130 access points. Status is worked out by checking whether each AP appears as a neighbour of any monitored switch.",
    why: "LogicMonitor doesn't monitor these APs directly, so the app infers their status from switch neighbour tables.",
    from: ["CDP/LLDP neighbour tables of the switches, checked every ~2 hours."],
    good: "Present as a neighbour → Online. Absent → Offline. This is inferred evidence, never a fabricated up/down flag.",
    related: ["cdp-lldp"] },

  // ---------------------------------------------------------------- Device Details
  { id: "device-detail", cat: "Device Details", name: "Device detail view", synonyms: ["device detail", "device page", "tabs"],
    short: "Everything about one device: health, interfaces, neighbours, routing, config.",
    what: "The full view for a single device — a metric ribbon (CPU, memory, uptime, OS) and tabs for health, ping quality, interfaces, VLANs, neighbours, OSPF, inventory, environment, alerts, config, gaps.",
    why: "For engineers to drill from an executive number down to the device.",
    good: "Tables show 'Not available from LogicMonitor' where a datasource isn't mapped — missing data is never shown as zero. Admins can fill gaps directly via read-only SSH.",
    related: ["health-data", "interfaces-table", "cdp-lldp", "ssh-gapfill", "monitoring-gaps"] },
  { id: "health-data", cat: "Device Details", name: "Health Data", synonyms: ["health", "cpu", "memory", "temperature", "os"],
    short: "The device's current health: CPU, memory, temperature, uptime, model, OS.",
    what: "The device's key health readings: how busy the processor (CPU) is, how much memory is used, temperature, uptime, model and OS version.",
    why: "To spot an overloaded or overheating device.",
    from: ["LogicMonitor datasources (CPU, memory, temperature sensors, uptime)."],
    good: "CPU and memory below ~85% are comfortable; sustained higher values are flagged.",
    related: ["ping-quality", "environmental", "uptime-vs-avail"] },
  { id: "ping-quality", cat: "Device Details", name: "Ping Quality", synonyms: ["ping", "latency", "loss", "probe"],
    short: "Reachability quality: latency, packet loss and 24-hour availability.",
    what: "How well the device answers probes: min/avg/max latency, packet loss, and its 24-hour availability.",
    why: "This is the raw material for availability and the SLA.",
    from: ["LogicMonitor's Ping datasource."],
    related: ["latency", "packet-loss", "availability"] },
  { id: "interfaces-table", cat: "Device Details", name: "Interfaces (device)", synonyms: ["interfaces", "ports", "duplex", "speed", "errors"],
    short: "Each interface's status, VLAN, duplex, speed, utilisation and errors.",
    what: "A table of the device's network ports with their status, VLAN, duplex, speed, utilisation, and error counts.",
    why: "To find a down port, a duplex mismatch, or a port with errors.",
    from: ["LogicMonitor's interface datasource; VLAN/duplex and error columns can be filled by admin SSH collection."],
    related: ["interface-util", "ssh-gapfill"] },
  { id: "cdp-lldp", cat: "Device Details", name: "CDP/LLDP Neighbors", synonyms: ["cdp", "lldp", "neighbors", "topology"],
    short: "Which devices are directly connected, drawn as a small topology.",
    what: "The directly-connected neighbours the device sees, using the CDP and LLDP protocols. Shown as a small map with this device at the centre.",
    why: "To understand physical connectivity and find where an AP or switch is attached.",
    from: ["LogicMonitor's CDP/LLDP datasources."],
    related: ["access-points", "device-detail"] },
  { id: "monitoring-gaps", cat: "Device Details", name: "Monitoring Gaps", synonyms: ["gaps", "missing", "not monitored"],
    short: "What LogicMonitor cannot see for this device — and how to fill it.",
    what: "Lists the tables LogicMonitor has no data for on this device (e.g. VLANs, spanning tree, alerts).",
    why: "So you know what's missing and why a tab is empty.",
    good: "An admin can pull the missing data directly from the device via read-only SSH, which fills these gaps until the next pull.",
    related: ["ssh-gapfill", "data-coverage"] },
  { id: "ssh-gapfill", cat: "Device Details", name: "Fill gaps from device (SSH)", synonyms: ["ssh", "show commands", "pull", "manual collect"],
    short: "Admins pull missing data straight from the device with read-only commands.",
    what: "An admin-only button that connects to the device over SSH (approved by push MFA) and runs read-only Cisco 'show' commands to fill the gaps LogicMonitor can't — VLANs, interface details, neighbours, inventory, routing, spanning tree, PoE, logs and config.",
    why: "Some data simply isn't in LogicMonitor; this gets it directly, safely.",
    good: "Strictly read-only — only 'show' commands, never any change. The password is used for one session and never stored. Device secrets in the config are removed before saving.",
    tech: "Results are saved and shown until the next pull. Also reads the device log to fill Alerts and produce Cisco-knowledge recommendations. Every pull also checks the device's OWN configured hostname (from its running-config or 'show version' banner) against what this record expects. If they don't match, a red banner appears — this catches LogicMonitor's management-IP-to-device mapping going stale (confirmed live 2026-08-12: one device's LM record silently pointed at a different physical switch after a network change), because the device itself can't lie about who it is the way an out-of-date inventory record can.",
    related: ["monitoring-gaps", "alerts", "recommendations"] },
  { id: "alerts", cat: "Device Details", name: "Alerts", synonyms: ["alerts", "syslog", "logs", "events"],
    short: "Events from the device log, with severity, source and message.",
    what: "Notable events from the device's own log (syslog): severity, the source, the event, and the message.",
    why: "Logs often explain why a device is unhealthy.",
    from: ["The device's log buffer, read via admin SSH ('show logging'). LogicMonitor's live alert stream is separate."],
    good: "Higher severity (Emergency/Alert/Critical/Error) matters most.",
    related: ["recommendations", "ssh-gapfill"] },
  { id: "recommendations", cat: "Device Details", name: "Recommendations", synonyms: ["recommendations", "what to do", "remediation", "advice"],
    short: "Why a device is in trouble and what to do, from a Cisco knowledge base.",
    what: "A prioritised list (P1/P2/P3) of the device's log events, each with a plain-English likely cause and a recommended read-only fix.",
    why: "It turns cryptic log codes into clear next steps.",
    from: ["The parsed device log matched against a built-in Cisco knowledge base for the fleet's platforms (Catalyst 9200/9300/9500, 2960/3750, ISR 4331)."],
    good: "All advice is read-only guidance — the app never changes the device.",
    related: ["alerts", "leadership-actions"] },
  { id: "config-backups", cat: "Device Details", name: "Configuration Backups", synonyms: ["config", "running config", "backup"],
    short: "The device configuration, with secrets removed.",
    what: "Shows whether the config is saved, and (via SSH) the running configuration text.",
    why: "For change control and troubleshooting.",
    good: "Any passwords, SNMP communities and keys are masked as <redacted> before the config is stored — device secrets are never kept.",
    related: ["ssh-gapfill"] },
  { id: "environmental", cat: "Device Details", name: "Environmental & PoE", synonyms: ["environment", "fan", "power", "temperature", "poe"],
    short: "Temperature, fans, power supplies and Power-over-Ethernet.",
    what: "The device's environment: temperature sensors, fans, power supplies, and PoE (power delivered to phones/APs over the network cable).",
    why: "A failed fan or power supply is a real hardware risk.",
    from: ["LogicMonitor sensors; PoE and more can be filled by admin SSH."],
    related: ["health-data", "ssh-gapfill"] },

  // ---------------------------------------------------------------- Reports
  { id: "reports", cat: "Reports", name: "Executive reports", synonyms: ["reports", "excel", "powerpoint", "export"],
    short: "One-click Excel and PowerPoint executive reports from the live numbers.",
    what: "The Export buttons on the Overview produce a Medline-branded Excel workbook and PowerPoint deck, filled with the current live numbers.",
    why: "For sharing with leadership offline.",
    good: "Every figure comes from the same analytics as the dashboard, so the reports reconcile with the app.",
    related: ["overview", "global-sla"] },

  // ---------------------------------------------------------------- Meta: formulas / algorithms / thresholds / colors / data / relationships
  { id: "formulas", cat: "Calculations & Formulas", name: "Formula library", synonyms: ["formula", "calculation", "math"],
    short: "Every formula the app uses, in one place.",
    what: "The core formulas: Availability = up ÷ observed × 100. Coverage = observed ÷ expected × 100. Packet loss = lost ÷ sent × 100. Average latency = sum of times ÷ count. MTTR = total repair time ÷ incidents. MTBF = total operating time ÷ failures.",
    why: "So any number can be traced to its math.",
    good: "Some values are provided directly by LogicMonitor (e.g. latency, interface counters) — the app doesn't recalculate those, it just presents and rolls them up.",
    related: ["availability", "coverage", "packet-loss", "latency", "mttr-mtbf"] },
  { id: "algorithms", cat: "Scores & Algorithms", name: "Scores & algorithms", synonyms: ["algorithm", "score", "how it works"],
    short: "How the derived scores are built (resilience tier, criticality, actions).",
    what: "The app derives a few scores: the resilience tier (from observed redundancy + availability, weakest-link across the fleet), the criticality split (from the importance you set), and the leadership actions (ranked by severity × business importance).",
    why: "So the logic behind each score is transparent.",
    good: "Missing evidence is never scored as zero — it's excluded and labelled instead.",
    related: ["resilience", "criticality", "leadership-actions"] },
  { id: "thresholds", cat: "Thresholds & Colors", name: "Thresholds", synonyms: ["threshold", "limit", "target"],
    short: "The bars that decide good/warning/critical.",
    what: "Key thresholds: SLA target 99.9%; coverage gate 90% (below it = Insufficient evidence); CPU/memory warning ~85%; interface high-utilisation ~80%; packet-loss warning ~2%.",
    why: "So you know when a number turns from green to red.",
    good: "The SLA target and coverage threshold are configurable settings.",
    related: ["colors", "sla", "coverage"] },
  { id: "colors", cat: "Thresholds & Colors", name: "Status colors", synonyms: ["colors", "green", "yellow", "red", "badge"],
    short: "What the colors and status words mean.",
    what: "Green = Healthy / target met. Amber/Yellow = needs attention / at risk. Red = Critical (down or fault). Grey = No data / unknown / not monitored.",
    why: "Color gives an at-a-glance read.",
    good: "Words match colors: HEALTHY, DEGRADED/AT RISK, CRITICAL, INSUFFICIENT EVIDENCE, NOT MONITORED.",
    related: ["thresholds", "insufficient-evidence"] },
  { id: "data-sources", cat: "Data Sources", name: "Data Sources", synonyms: ["source", "logicmonitor", "where data comes from"],
    short: "Where every number comes from.",
    what: "Most data comes from LogicMonitor (read-only API): availability, latency, CPU, memory, interfaces, topology, OSPF. The app's own database stores the daily rollups, sites, business units, and settings. Some device detail is pulled directly from devices via admin read-only SSH.",
    why: "So you can trust the origin of every number.",
    good: "The app only ever reads from LogicMonitor and devices — it never changes them. Credentials are never shown, logged, or returned.",
    related: ["getting-started", "ssh-gapfill", "data-coverage"] },
  { id: "relationships", cat: "Relationships", name: "How metrics affect each other", synonyms: ["relationship", "affects", "chain", "impact"],
    short: "A device outage flows up into site, fleet, SLA and Global Status.",
    what: "Metrics are connected. A device going offline lowers its availability, which can lower its site's availability, which can lower the fleet's availability and the SLA, which can lower the Global SLA Status. Separately, a routing/redundancy loss lowers the resilience tier.",
    why: "So you can trace why a top-level number moved.",
    example: "Device offline → device availability ↓ → site availability ↓ → fleet/SLA ↓ → Global SLA Status ↓.",
    related: ["global-sla", "availability", "site-reliability", "resilience"] },
  { id: "rounding", cat: "Calculations & Formulas", name: "Rounding", synonyms: ["rounding", "decimals", "why different", "precision"],
    short: "One rounding rule everywhere: 2 decimals, trailing zeros trimmed.",
    what: "Every percentage in the app — on screen, in Excel and in PowerPoint — is rounded the same way: to at most 2 decimal places, with trailing zeros removed. So 100.000% shows as 100%, 99.9200% shows as 99.92%, and 99.9000% shows as 99.9%.",
    why: "Three decimals are meaningless to a reader and made the same number look different in different places. One shared rule means a figure you quote from the dashboard is the identical figure in the board pack.",
    formula: "Displayed = round(exact value, 2 decimals), then trim trailing zeros, then add '%'.",
    example: "The exact stored value 99.97536% displays everywhere as 99.98%.",
    good: "Rounding is presentation only. All calculations use the full-precision value internally and are never done on already-rounded numbers, so rounding can never accumulate into a wrong total.",
    tech: "Implemented once per language and shared by every consumer: frontend/src/format.ts (fmtPct) for the UI, and sla.fmt_pct() for Excel/PowerPoint and generated narrative text.",
    related: ["time-periods", "global-sla", "reports"] },
  { id: "time-periods", cat: "Calculations & Formulas", name: "Time periods", synonyms: ["period", "7 day", "30 day", "ytd", "wtd"],
    short: "Different time windows give different (all correct) numbers.",
    what: "Numbers are computed over a window: 7-day, 30-day, week-to-date (WTD), or year-to-date (YTD). Changing the window changes the number.",
    why: "A 7-day availability of 99.99% and a 30-day of 99.6% can both be correct — they cover different periods.",
    related: ["global-sla", "rounding", "commissioning"] },
];

export const GLOSSARY: { term: string; def: string }[] = [
  { term: "API", def: "A way for two programs to exchange data. The app reads LogicMonitor through its API." },
  { term: "Availability", def: "How much of the monitored time the service was working. Shown as a percentage." },
  { term: "Best-path availability", def: "A branch's availability counting it as up whenever its best-covered device had a path — the redundancy-aware view (a backup carrying the site still counts as up). Shown on Path Resilience." },
  { term: "Pooled availability", def: "The strict per-device average for a branch (all devices' up-minutes over all observed-minutes). Any device's downtime lowers it, even if a backup carried the site." },
  { term: "Rolling 7-day", def: "Availability over the trailing 7 days (last same-weekday to now). Always has a full week of data, so it never reads 'insufficient' early in the week." },
  { term: "Week-to-date (WTD)", def: "Availability from this Monday 00:00 to now. Reads 'insufficient' on Monday/Tuesday until enough of the week is observed." },
  { term: "Previous week", def: "Availability for the last complete calendar week (previous Monday to Sunday) — the number used for weekly reporting." },
  { term: "Day/week boundary timezone", def: "'Today', 'this week', and every daily rollup use ONE company-wide clock (Pacific time), not each site's local timezone. A Halifax or Guelph site's day turns over a few hours before its own local midnight. This affects only which calendar day/week an event is filed under, not the underlying up/down minutes." },
  { term: "Throughput", def: "How much traffic is flowing, in bits per second. Estimated as link speed x utilisation, counting both directions (in + out)." },
  { term: "Busy-hour peak", def: "The single highest hourly fleet throughput over a window (e.g. 7 days) — the busiest moment, not an instantaneous snapshot." },
  { term: "95th percentile (p95)", def: "The throughput level exceeded only 5% of the time over the window — a robust 'typical busy' level that ignores one-off spikes. The same method carriers bill on." },
  { term: "WAN circuit", def: "A provider link (e.g. Bell 100M, LTE, DMVPN) that carries a branch's traffic to the wider network / internet." },
  { term: "Floating static route", def: "A backup route with a higher administrative distance that only installs when the primary path fails — a common WAN failover method." },
  { term: "IP SLA tracking", def: "A device probe (e.g. ping to the next-hop) that a route can watch, so a floating backup takes over only when the primary is really down." },
  { term: "HSRP / VRRP (FHRP)", def: "First-Hop Redundancy Protocols: two devices share one virtual gateway IP so hosts keep their default gateway if one device fails." },
  { term: "EtherChannel", def: "Several physical links bundled into one logical link for more bandwidth and redundancy (LACP negotiates it safely)." },
  { term: "Stacked switch", def: "Two or more switches acting as one, sharing a control plane — so the group survives one member failing." },
  { term: "Dual-homed", def: "Connected by two uplinks (often to both members of a stack), so the device stays up if one uplink fails." },
  { term: "Path Resilience", def: "The admin/engineer page showing, per branch, redundancy-aware availability, failover posture, provider circuits, best routes, and recommended fixes." },
  { term: "BGP", def: "A routing protocol routers use to tell each other which network paths are available, often with providers." },
  { term: "CDP / LLDP", def: "Protocols that let a device see its directly-connected neighbours." },
  { term: "CCIE runbook", def: "An administrator-only, evidence-first procedure: verify the event, correct its root cause in an approved change, then re-check the same evidence. The app never runs the commands." },
  { term: "Coverage", def: "How much of the expected time we actually have data for. Below 90% we don't publish availability." },
  { term: "Criticality", def: "How important a device is to the business: Critical, High, Medium or Low. It is different from the device's current health." },
  { term: "Downtime", def: "Time the service was not working." },
  { term: "Interface", def: "A network port on a switch or router." },
  { term: "Local / remote port", def: "The interface on the device being viewed, and the far-end interface reported by CDP/LLDP. A remote port is omitted when it was not actually collected." },
  { term: "Jitter", def: "How much the delay varies. Steady delay is better." },
  { term: "Latency", def: "Delay — how long a packet takes to travel and get a reply. Lower is better." },
  { term: "LogicMonitor", def: "The monitoring system that collects data from the network. This app reads it, read-only." },
  { term: "MTBF", def: "Mean Time Between Failures — the average time between failures. Higher is better." },
  { term: "MTTR", def: "Mean Time To Recover — the average time to fix an incident. Lower is better." },
  { term: "OSPF", def: "A routing protocol that helps routers find the best paths inside a network." },
  { term: "Packet loss", def: "The share of packets that did not arrive. 0% is best." },
  { term: "PoE", def: "Power over Ethernet — power delivered to phones/APs over the network cable." },
  { term: "Redundancy", def: "A backup path or device so the network keeps working if one part fails." },
  { term: "Reliability", def: "How often something fails — not just whether it was working." },
  { term: "Resilience", def: "How well the network keeps working when something fails." },
  { term: "SLA", def: "Service Level Agreement — the level of service we expect, e.g. 99.9% availability." },
  { term: "Static route", def: "A path set manually by an engineer, instead of learned automatically." },
  { term: "Stack", def: "Several physical switches joined to act as one logical device." },
  { term: "Telemetry", def: "Measurements collected from network devices (delay, loss, load, etc.)." },
  { term: "Uptime", def: "How long a device has run since its last restart. Different from availability." },
  { term: "WAN", def: "Wide Area Network — the links between sites, often via a provider." },
];

export const FAQ: { q: string; a: string; link?: string }[] = [
  { q: "Why is Global SLA Status not 100%?", a: "Because at least one device had some downtime, or a site had reduced availability, over the last 30 days. Open Global SLA Status to see the live reasons.", link: "global-sla" },
  { q: "Why is Availability different from Uptime?", a: "Uptime is how long a device ran since its last restart. Availability is how reachable the service was. A device can be 'up' but unreachable.", link: "uptime-vs-avail" },
  { q: "Why is Reliability lower than Availability?", a: "Availability asks 'was it working?'. Reliability asks 'how often did it fail?'. Many short failures can keep availability high but hurt reliability.", link: "reliability" },
  { q: "Why did my SLA number change when I picked 30 days?", a: "Different time periods cover different events, so they give different (all correct) numbers.", link: "time-periods" },
  { q: "Why does the Overview show 99.9% but another page shows 99.94%?", a: "Rounding. The exact value is the same; one place shows fewer decimals.", link: "rounding" },
  { q: "Why does a site show 'since Jun 2026'?", a: "That site was first monitored in June, so its year-to-date is measured from then — not from January when it didn't exist.", link: "commissioning" },
  { q: "Why does an offline device affect the site score?", a: "A site's availability combines its devices. If one goes offline, the site's availability can drop.", link: "relationships" },
  { q: "What does 'Not monitored' mean?", a: "LogicMonitor has no data for that metric on this fleet (e.g. BGP, jitter). The app says so instead of showing a fake zero.", link: "data-coverage" },
  { q: "What is a good latency?", a: "On a LAN, single-digit milliseconds. Tens of milliseconds is fine for most WAN links. Sustained high values need investigation.", link: "latency" },
  { q: "Why can an interface be up but unhealthy?", a: "It can be up but running at high utilisation, dropping packets, or showing errors. Check its utilisation and error columns.", link: "interfaces-table" },
  { q: "How often is data refreshed?", a: "Devices are re-collected every 30 minutes. Snapshot Utilisation is refreshed in the page every minute and is withheld if its oldest contributing device poll exceeds one hour. The SLA rollup runs every 6 hours, resilience every 12 hours, and access-point status every 2 hours.", link: "data-sources" },
  { q: "Are the WAN provider routers part of our SLA?", a: "No. They belong to the carriers and are shown for visibility only, completely separate from Medline's metrics.", link: "wan-providers" },
];
