import React,{useEffect,useState}from'react';

type Props={token:string};

export default function InventoryFleet({token}:Props){
  const[data,setData]=useState<any>({items:[],total:0,page:1,pages:1});
  const[q,setQ]=useState('');const[site,setSite]=useState('');const[type,setType]=useState('');const[status,setStatus]=useState('');const[enabled,setEnabled]=useState('');
  const load=async(page=1)=>{
    const params=new URLSearchParams({page:String(page),page_size:'25'});
    if(q)params.set('q',q);if(site)params.set('site',site);if(type)params.set('device_type',type);if(status)params.set('match_status',status);if(enabled)params.set('enabled',enabled);
    const response=await fetch('/api/v1/inventory/devices?'+params,{headers:{Authorization:`Bearer ${token}`}});
    if(response.ok)setData(await response.json());
  };
  useEffect(()=>{load()},[]);
  return <section className="panel inventory-panel"><div className="panelhead"><div><h2>Device Inventory</h2><p className="muted">Controlled local inventory synchronized read-only from LogicMonitor</p></div><span className="pill">{data.total} records</span></div><div className="inventory-controls"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/></label><label>Site<input value={site} onChange={e=>setSite(e.target.value.toUpperCase())} placeholder="All"/></label><label>Device type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All</option><option>DSW</option><option>ASW</option><option>RTR</option><option>AP</option></select></label><label>Match status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option>Matched</option><option>Pending LogicMonitor Match</option></select></label><label>State<select value={enabled} onChange={e=>setEnabled(e.target.value)}><option value="">All</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><button onClick={()=>load()}>Apply Filters</button></div><div className="table-scroll"><table><thead><tr>{['Complete Device Name','Site Code','City','Zone','Device Type','Number','Role','Model','Management IP','LogicMonitor ID','Match Status','Criticality','Enabled','Last Synchronized'].map(x=><th>{x}</th>)}</tr></thead><tbody>{data.items.map((d:any)=><tr><td><b>{d.generated_name}</b></td><td>{d.site_code}</td><td>{d.city}</td><td>{d.zone}</td><td>{d.device_type}</td><td>{d.device_number}</td><td>{d.role}</td><td>{d.model||'Pending'}</td><td>{d.management_ip||'Pending'}</td><td>{d.logicmonitor_device_id||'—'}</td><td><span className={'status-badge '+(d.logicmonitor_match_status==='Matched'?'ok':'warn')}>{d.logicmonitor_match_status}</span></td><td>{d.criticality}</td><td>{d.enabled?'Enabled':'Disabled'}</td><td>{d.last_synchronized?new Date(d.last_synchronized).toLocaleString():'Never'}</td></tr>)}</tbody></table></div>{!data.items.length&&<div className="empty">No inventory devices match the selected filters.</div>}<div className="pagination"><button disabled={data.page<=1} onClick={()=>load(data.page-1)}>Previous</button><span>Page {data.page} of {data.pages}</span><button disabled={data.page>=data.pages} onClick={()=>load(data.page+1)}>Next</button></div></section>
}
